[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile.deploy"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 3000

[environments.production]
PORT = "3000"
NODE_ENV = "production"