services:
  - type: web
    name: cobol-credit-api
    runtime: docker
    repo: https://github.com/jfuginay/cobol-credit-api
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000